;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="UI.Action.Quit To Desktop",NewTagName="UI.Action.QuitToDesktop")
+GameplayTagRedirects=(OldTagName="UI.Action.Exit To Main Menu",NewTagName="UI.Action.ExitToMainMenu")
+GameplayTagRedirects=(OldTagName="Experience.Gameplay",NewTagName="Experience.Main")
+GameplayTagRedirects=(OldTagName="Experience.FrontEnd",NewTagName="Experience.Startup")
+GameplayTagList=(Tag="Experience.Main",DevComment="")
+GameplayTagList=(Tag="Experience.Startup",DevComment="")
+GameplayTagList=(Tag="Stat",DevComment="")
+GameplayTagList=(Tag="UI.Action.Credits",DevComment="")
+GameplayTagList=(Tag="UI.Action.ExitToMainMenu",DevComment="")
+GameplayTagList=(Tag="UI.Action.Play",DevComment="")
+GameplayTagList=(Tag="UI.Action.QuitToDesktop",DevComment="")
+GameplayTagList=(Tag="UI.Action.Resume",DevComment="")
+GameplayTagList=(Tag="UI.Action.Settings",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="Used for anything vital to gameplay (Ex. health bars or ability cooldowns).")
+GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="Used for toggleable menus relating to gameplay (Ex. a scoreboard)".)
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="Used for non-gameplay menus (Ex. main menu or settings screen)".)
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="Used for high-priority pop-ups (Ex. confirmations, controller disconnection warnings).")

