;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="UI.Action.Quit To Desktop",NewTagName="UI.Action.QuitToDesktop")
+GameplayTagRedirects=(OldTagName="UI.Action.Exit To Main Menu",NewTagName="UI.Action.ExitToMainMenu")
+GameplayTagList=(Tag="UI.Action.Credits",DevComment="")
+GameplayTagList=(Tag="UI.Action.ExitToMainMenu",DevComment="")
+GameplayTagList=(Tag="UI.Action.Play",DevComment="")
+GameplayTagList=(Tag="UI.Action.QuitToDesktop",DevComment="")
+GameplayTagList=(Tag="UI.Action.Resume",DevComment="")
+GameplayTagList=(Tag="UI.Action.Settings",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="")
+GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="")

